### ISSUE TITLE
Language Filters not working as expected

### ISSUE THREAD

**Issue by webbj74** [mstdn/Mastodon#1]
### Steps to reproduce the problem

1. Visit https://mstdn.social/settings/preferences/other 
2. Select "English" and "Français".
3. Click "SAVE CHANGES".
4. View "Local" or "Federated" timelines.
5. Toots that are not in "English" or "Français" are still present.

Examples of posts I expected to be filtered:
Local: https://mstdn.social/web/@lgcjlinms/108216513344781537
Federated: https://mstdn.social/web/@Mmdreza@mastodon.social/108216486131821249

### Expected behaviour

If I select one or more languages, I expect to not see toots in languages I left unchecked.

### Actual behaviour

Nothing appears to be filtered

### Specifications

Viewing on https://mstdn.social/ via Firefox (v3.5.1+glitch at time this issue is filed).

**Comment by mstdn** [comment]
This should be working better now! There is a new lang system for posting toots so it will get better set in the right language :-)  I'll keep an eye out on this one!

**Comment by johnno66** [comment]
Sorry to report this is still an issue (v3.5.3+glitch).
Language indicator now appear on top of toots, but the filters are still non-functional.
Would be great to have this working properly as the volume of traffic on Mastodon is increasing ;-)
